mods:
  bots:
    limit_connects: true
    max_conn_per_ip: 2
  world:
    enabled: true
    enderchests: true
    block_explosions: true
    entity_block_changes: true
    fire_spread: true
    cobblestone_generators: true
    bedbombs: true
  elevator:
    enabled: true
  mob-stacking:
    enabled: true
    tag-prefix: '&ax'
    stack-interval: 5
    max-stack-size: 100
    breed-cooldown: 30
    stack-types:
      - 'ZOMBIE'
      - 'SKELETON'
      - 'SPIDER'
      - 'CAVE_SPIDER'
      - 'COW'
      - 'CHICKEN'
      - 'PIG'
      - 'RABBIT'
      - 'SHEEP'
  kit-limits:
    enabled: true
    enchantments:
      THORNS:
        disabled: true
        max-level: 0
      KNOCKBACK:
        disabled: true
        max-level: 0
      ARROW_KNOCKBACK:
        disabled: true
        max-level: 0
    banned-potions:
      - '373:16452'
      - '373:16458'
      - '373:16456'
      - '373:16460'
      - '373:16428'
  knockback:
    enabled: true
    values:
      horizontal: 1.0
      vertical: 1.0
  potions:
    enabled: true
    old_health: true
    old_strength: true
    old_regen: true
  xp:
    enabled: true
  mining:
    enabled: true
    findables:
      DIAMOND_ORE:
        inside: 'STONE'
        environment: 'NORMAL'
        min_vein: 3
        max_vein: 8
        min_spawn_height: 0
        max_spawn_height: 16
        odds: '1:1250'
      EMERALD_ORE:
        inside: 'STONE'
        environment: 'NORMAL'
        min_vein: 1
        max_vein: 8
        min_spawn_height: 0
        max_spawn_height: 16
        odds: '1:1000'
      GOLD_ORE:
        inside: 'STONE'
        environment: 'NORMAL'
        min_vein: 2
        max_vein: 10
        min_spawn_height: 0
        max_spawn_height: 32
        odds: '1:800'
      REDSTONE_ORE:
        inside: 'STONE'
        environment: 'NORMAL'
        min_vein: 4
        max_vein: 16
        min_spawn_height: 0
        max_spawn_height: 32
        odds: '1:600'
      LAPIS_ORE:
        inside: 'STONE'
        environment: 'NORMAL'
        min_vein: 4
        max_vein: 16
        min_spawn_height: 0
        max_spawn_height: 32
        odds: '1:600'
      IRON_ORE:
        inside: 'STONE'
        environment: 'NORMAL'
        min_vein: 4
        max_vein: 16
        min_spawn_height: 0
        max_spawn_height: 32
        odds: '1:500'
      COAL_ORE:
        inside: 'STONE'
        environment: 'NORMAL'
        min_vein: 4
        max_vein: 16
        min_spawn_height: 0
        max_spawn_height: 32
        odds: '1:400'
      QUARTZ_ORE:
        inside: 'NETHERRACK'
        environment: 'NETHER'
        min_vein: 4
        max_vein: 16
        min_spawn_height: 0
        max_spawn_height: 256
        odds: '1:600'
      GLOWSTONE:
        inside: 'NETHERRACK'
        environment: 'NETHER'
        min_vein: 2
        max_vein: 8
        min_spawn_height: 0
        max_spawn_height: 256
        odds: '1:800'